import { useEffect } from "react";
import Head from 'next/head'
import Router from 'next/router'

import Navbar from '../../components/navbar'
import Todo from '../../components/todo'
import Footer from '../../components/footer'
import { verifyToken } from '../../hooks/useLocalStorage'

export default function AppHome() {
  const verifiedtoken = verifyToken();

  useEffect(() => {
    
    if(verifiedtoken === false){
      Router.push(`/login?return_url=app`)
    }
    
  }, [verifiedtoken])

  return (
    <>
      <div className='bg-gray-900 w-full px-6 mx-auto'>
        <Head>
          <title>Todo's App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <Todo />
        <Footer />
      </div>
    </>
  )
}
