import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Todo from '../components/todo'

export default function AppHome() {

  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />
        <Todo />
       
       
        <footer className={styles.footer}>
          <a
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  )
}
