import { useState } from "react";
import { useForm } from "react-hook-form";
import axios from "axios";
import Head from 'next/head'
import Router from 'next/router'

import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

const loginUrl = `${process.env.NEXT_PUBLIC_API_GATEWAY_URL}/login`;

export default function Signup() {
  const { register, handleSubmit } = useForm();
  const [message, setMessage] = useState("");

  const onSubmit = data => {
    const requestConfg = {
      headers: {
        'x-api-key': process.env.NEXT_PUBLIC_API_KEY
      }
    }
    const requestBody = {
      email: data.email,
      password: data.password
    }

    if(data.email || data.password){
      axios.post(loginUrl, requestBody, requestConfg).then(response => {
        localStorage.setItem('user', JSON.stringify(response.data.user));
        localStorage.setItem('token', response.data.token);

        Router.push('/app')
      }).catch(error => {
        console.log(error);
        if(error.response.status === 401 || error.response.status === 403){
          setMessage(error.response.data.message);
        }else{
          setMessage('sorry... the backend server is down! please try again later');
        }
      })
    }else{
      setMessage('All fields are required !');
    }
  };


  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <main className={styles.main}>
          
          <div className="py-12 px-12 bg-[#10173C] rounded-2xl shadow-xl z-20">
            <form onSubmit={handleSubmit(onSubmit)}>
              <div>
                <h1 className="text-3xl font-bold text-center mb-4 text-white">Login An Account</h1>
                <p className="w-80 text-center text-sm mb-8 font-semibold text-gray-300 tracking-wide">Create an
                  account to enjoy all the services without any ads for free!</p>
              </div>
              
              <div className="space-y-4">
                <input {...register("email")} placeholder="Email Addres" type="text" className="block text-sm py-3 px-4 rounded-lg w-full border outline-none"/>
                <input {...register("password")} placeholder="Password" type="password" className="block text-sm py-3 px-4 rounded-lg w-full border outline-none"/>
              </div>

              <div className="text-center mt-6">
                <button type="submit" className="py-3 w-64 text-xl text-white bg-purple-400 rounded-2xl">Login Account</button>
                <p className="mt-4 text-sm text-black">Already Have An Account? <span className="underline cursor-pointer"> Sign In</span></p>
                <p>{message}</p>
              </div>
            </form>
          </div>

        </main>
      </div>
    </>
  )
}
