import { useForm } from "react-hook-form";
import axios from "axios";
import Head from 'next/head'
import toast from 'react-hot-toast';

import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'

const registerUrl = `${process.env.NEXT_PUBLIC_API_GATEWAY_URL}/register`;

export default function Signup() {
  const { register, handleSubmit } = useForm();

  const onSubmit = data => {
    const requestConfg = {
      headers: {
        'x-api-key': process.env.NEXT_PUBLIC_API_KEY
      }
    }
    const requestBody = {
      email: data.email,
      password: data.password
    }

    if(data.email || data.password){
      axios.post(registerUrl, requestBody, requestConfg).then(response => {
        toast.success('Successfully registered', {
          duration: 2000,
          position: 'top-center',
        });
      }).catch(error => {
        if(error.response.status === 401){
          toast.error(error.response.data.message, {
            duration: 2000,
            position: 'top-center',
          });
        }else{
          toast.error("sorry... the backend server is down! please try again later", {
            duration: 2000,
            position: 'top-center',
          });
        }
      })
    }else{
      toast.error("All fields are required !", {
        duration: 2000,
        position: 'top-center',
      });
    }
  };


  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Signup</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar />

        <main className={styles.main}>
          
          <div className="py-12 px-12 bg-[#10173C] rounded-2xl shadow-xl z-20">
            <form onSubmit={handleSubmit(onSubmit)}>
              <div>
                <h1 className="text-3xl mb-8 font-bold text-center text-white">Create an Account</h1>
              </div>
              
              <div className="space-y-4">
                <input {...register("email")} placeholder="Email Address" type="text" className="block bg-transparent border-gray-700 text-sm py-3 px-4 rounded-lg w-full border outline-none"/>
                <input {...register("password")} placeholder="Password" type="password" className="block bg-transparent border-gray-700 text-sm py-3 px-4 rounded-lg w-full border outline-none"/>
              </div>

              <div className="text-center mt-6">
                <button type="submit" className="text-white font-bold text-sm bg-gradient-to-b from-[#4D13C0] to-[#2D0885] px-6 py-3 rounded-md">Create Account</button>
                <p className="mt-4 text-sm text-gray-500">Already have an account ? <a href="/login" className="underline cursor-pointer"> Sign In</a></p>
              </div>
            </form>
          </div>

        </main>
      </div>
    </>
  )
}
